/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as riddleQuestSol from "./RiddleQuest.sol";
export * as riddleVerifierSol from "./RiddleVerifier.sol";
