/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as riddleQuestHubSol from "./RiddleQuestHub.sol";
export * as riddleVerifierSol from "./RiddleVerifier.sol";
