/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface QuestInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "bounty"
      | "getMetadata"
      | "solutionHash"
      | "solved"
      | "submitProof"
      | "verifier"
      | "winner"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ProofSubmitted" | "QuestSolved"
  ): EventFragment;

  encodeFunctionData(functionFragment: "bounty", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getMetadata",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "solutionHash",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "solved", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "submitProof",
    values: [BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;
  encodeFunctionData(functionFragment: "winner", values?: undefined): string;

  decodeFunctionResult(functionFragment: "bounty", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "solutionHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "solved", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "winner", data: BytesLike): Result;
}

export namespace ProofSubmittedEvent {
  export type InputTuple = [solver: AddressLike, success: boolean];
  export type OutputTuple = [solver: string, success: boolean];
  export interface OutputObject {
    solver: string;
    success: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuestSolvedEvent {
  export type InputTuple = [solver: AddressLike, bounty: BigNumberish];
  export type OutputTuple = [solver: string, bounty: bigint];
  export interface OutputObject {
    solver: string;
    bounty: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Quest extends BaseContract {
  connect(runner?: ContractRunner | null): Quest;
  waitForDeployment(): Promise<this>;

  interface: QuestInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bounty: TypedContractMethod<[], [bigint], "view">;

  getMetadata: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, boolean] & {
        _verifier: string;
        _solutionHash: string;
        _winner: string;
        _bounty: bigint;
        _solved: boolean;
      }
    ],
    "view"
  >;

  solutionHash: TypedContractMethod<[], [string], "view">;

  solved: TypedContractMethod<[], [boolean], "view">;

  submitProof: TypedContractMethod<
    [_proof: BytesLike, _publicInputs: BytesLike[]],
    [void],
    "nonpayable"
  >;

  verifier: TypedContractMethod<[], [string], "view">;

  winner: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bounty"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMetadata"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, boolean] & {
        _verifier: string;
        _solutionHash: string;
        _winner: string;
        _bounty: bigint;
        _solved: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "solutionHash"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "solved"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "submitProof"
  ): TypedContractMethod<
    [_proof: BytesLike, _publicInputs: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "winner"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ProofSubmitted"
  ): TypedContractEvent<
    ProofSubmittedEvent.InputTuple,
    ProofSubmittedEvent.OutputTuple,
    ProofSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "QuestSolved"
  ): TypedContractEvent<
    QuestSolvedEvent.InputTuple,
    QuestSolvedEvent.OutputTuple,
    QuestSolvedEvent.OutputObject
  >;

  filters: {
    "ProofSubmitted(address,bool)": TypedContractEvent<
      ProofSubmittedEvent.InputTuple,
      ProofSubmittedEvent.OutputTuple,
      ProofSubmittedEvent.OutputObject
    >;
    ProofSubmitted: TypedContractEvent<
      ProofSubmittedEvent.InputTuple,
      ProofSubmittedEvent.OutputTuple,
      ProofSubmittedEvent.OutputObject
    >;

    "QuestSolved(address,uint256)": TypedContractEvent<
      QuestSolvedEvent.InputTuple,
      QuestSolvedEvent.OutputTuple,
      QuestSolvedEvent.OutputObject
    >;
    QuestSolved: TypedContractEvent<
      QuestSolvedEvent.InputTuple,
      QuestSolvedEvent.OutputTuple,
      QuestSolvedEvent.OutputObject
    >;
  };
}
