/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RiddleQuestInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "bounty"
      | "deadline"
      | "getFullMetadata"
      | "prompt"
      | "solutionHash"
      | "solved"
      | "status"
      | "submitProof"
      | "title"
      | "verifier"
      | "winner"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ProofAttempt" | "QuestInitialized" | "QuestSolved"
  ): EventFragment;

  encodeFunctionData(functionFragment: "bounty", values?: undefined): string;
  encodeFunctionData(functionFragment: "deadline", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getFullMetadata",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "prompt", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "solutionHash",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "solved", values?: undefined): string;
  encodeFunctionData(functionFragment: "status", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "submitProof",
    values: [BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(functionFragment: "title", values?: undefined): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;
  encodeFunctionData(functionFragment: "winner", values?: undefined): string;

  decodeFunctionResult(functionFragment: "bounty", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deadline", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFullMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "prompt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "solutionHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "solved", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "status", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "title", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "winner", data: BytesLike): Result;
}

export namespace ProofAttemptEvent {
  export type InputTuple = [solver: AddressLike, ok: boolean];
  export type OutputTuple = [solver: string, ok: boolean];
  export interface OutputObject {
    solver: string;
    ok: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuestInitializedEvent {
  export type InputTuple = [
    title: string,
    bounty: BigNumberish,
    deadline: BigNumberish
  ];
  export type OutputTuple = [title: string, bounty: bigint, deadline: bigint];
  export interface OutputObject {
    title: string;
    bounty: bigint;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuestSolvedEvent {
  export type InputTuple = [solver: AddressLike, bounty: BigNumberish];
  export type OutputTuple = [solver: string, bounty: bigint];
  export interface OutputObject {
    solver: string;
    bounty: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RiddleQuest extends BaseContract {
  connect(runner?: ContractRunner | null): RiddleQuest;
  waitForDeployment(): Promise<this>;

  interface: RiddleQuestInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bounty: TypedContractMethod<[], [bigint], "view">;

  deadline: TypedContractMethod<[], [bigint], "view">;

  getFullMetadata: TypedContractMethod<
    [],
    [
      [string, string, bigint, bigint, bigint, string] & {
        _title: string;
        _prompt: string;
        _bounty: bigint;
        _deadline: bigint;
        _status: bigint;
        _winner: string;
      }
    ],
    "view"
  >;

  prompt: TypedContractMethod<[], [string], "view">;

  solutionHash: TypedContractMethod<[], [string], "view">;

  solved: TypedContractMethod<[], [boolean], "view">;

  status: TypedContractMethod<[], [bigint], "view">;

  submitProof: TypedContractMethod<
    [_proof: BytesLike, _publicInputs: BytesLike[]],
    [void],
    "nonpayable"
  >;

  title: TypedContractMethod<[], [string], "view">;

  verifier: TypedContractMethod<[], [string], "view">;

  winner: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bounty"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deadline"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getFullMetadata"
  ): TypedContractMethod<
    [],
    [
      [string, string, bigint, bigint, bigint, string] & {
        _title: string;
        _prompt: string;
        _bounty: bigint;
        _deadline: bigint;
        _status: bigint;
        _winner: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "prompt"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "solutionHash"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "solved"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "status"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitProof"
  ): TypedContractMethod<
    [_proof: BytesLike, _publicInputs: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "title"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "winner"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ProofAttempt"
  ): TypedContractEvent<
    ProofAttemptEvent.InputTuple,
    ProofAttemptEvent.OutputTuple,
    ProofAttemptEvent.OutputObject
  >;
  getEvent(
    key: "QuestInitialized"
  ): TypedContractEvent<
    QuestInitializedEvent.InputTuple,
    QuestInitializedEvent.OutputTuple,
    QuestInitializedEvent.OutputObject
  >;
  getEvent(
    key: "QuestSolved"
  ): TypedContractEvent<
    QuestSolvedEvent.InputTuple,
    QuestSolvedEvent.OutputTuple,
    QuestSolvedEvent.OutputObject
  >;

  filters: {
    "ProofAttempt(address,bool)": TypedContractEvent<
      ProofAttemptEvent.InputTuple,
      ProofAttemptEvent.OutputTuple,
      ProofAttemptEvent.OutputObject
    >;
    ProofAttempt: TypedContractEvent<
      ProofAttemptEvent.InputTuple,
      ProofAttemptEvent.OutputTuple,
      ProofAttemptEvent.OutputObject
    >;

    "QuestInitialized(string,uint256,uint256)": TypedContractEvent<
      QuestInitializedEvent.InputTuple,
      QuestInitializedEvent.OutputTuple,
      QuestInitializedEvent.OutputObject
    >;
    QuestInitialized: TypedContractEvent<
      QuestInitializedEvent.InputTuple,
      QuestInitializedEvent.OutputTuple,
      QuestInitializedEvent.OutputObject
    >;

    "QuestSolved(address,uint256)": TypedContractEvent<
      QuestSolvedEvent.InputTuple,
      QuestSolvedEvent.OutputTuple,
      QuestSolvedEvent.OutputObject
    >;
    QuestSolved: TypedContractEvent<
      QuestSolvedEvent.InputTuple,
      QuestSolvedEvent.OutputTuple,
      QuestSolvedEvent.OutputObject
    >;
  };
}
