export const placeHolderTitles = [
    "The Sphinx's Cipher",
    "Ethereum's Enigma",
    "Blockchain Brainteaser",
    "Cryptic Conundrum",
    "The Web3 Labyrinth",
    "Digital Riddle Vault",
    "The Solidity Secret",
    "Quantum Quandary",
    "The Miner's Mystery",
    "Decentralized Dilemma",
    "NFT Nebula Puzzle",
    "The Crypto Catacombs",
    "Smart Contract Conundrum",
    "The Merkle Tree Maze",
    "Validator's Venture",
    "The Blockchain Odyssey",
    "Metamask Mysteries",
    "The Consensus Challenge",
    "Wallet Wisdom Test",
    "The Gas Fee Gauntlet",
    "Zero-Knowledge Puzzle",
    "The Hash Function Hunt",
    "DeFi Detective Case",
    "The Staking Saga",
    "Protocol Paradox",
    "The Governance Gambit",
    "Layer-2 Labyrinth",
    "The Oracle Odyssey",
    "Token Treasure Hunt",
    "The Mnemonic Mystery",
    "Private Key Puzzle",
    "The DAO Dilemma",
    "Cryptographic Crossroads",
    "The Airdrop Adventure",
    "Metaverse Mysteries",
    "The Hardhat Heist",
    "Solana's Secrets",
    "The Polygon Puzzle",
    "Avalanche Enigma",
    "The Chainlink Challenge",
  ]
export const placeHolderExcerpts = [
    "Crack the code, claim your crypto reward!",
    "Solve this puzzle and walk away with the bounty.",
    "Your wit is the key to unlocking this treasure.",
    "Test your blockchain knowledge and earn rewards.",
    "Decipher the clues, collect the crypto prize.",
    "Sharpen your mind and fill your wallet.",
    "Puzzles with payouts - are you clever enough?",
    "Riddles worth solving - literally.",
    "Your next crypto payday is just one solution away.",
    "Brain power converts directly to token rewards here.",
    "Unravel the mystery and claim your digital fortune.",
    "Where intellect meets incentive - solve and earn.",
    "The smartest way to earn crypto: solve this quest.",
    "A challenge for your mind, a reward for your wallet.",
    "Decode the enigma, unlock the blockchain bounty.",
    "Prove your problem-solving prowess for profit.",
    "This riddle's solution comes with a token reward.",
    "Exercise your brain cells and earn cryptocurrency.",
    "The path to rewards is paved with clever solutions.",
    "Intellectual challenges with financial benefits.",
    "Crack this Web3 conundrum for crypto compensation.",
    "Your crypto treasure awaits behind this puzzle.",
    "Solve the unsolvable, claim the unclaimed.",
    "Where riddles and rewards intersect.",
    "Think, solve, earn - in that exact order.",
    "Blockchain bounties for brilliant minds.",
    "The ultimate test of wit with crypto at stake.",
    "Decipher the digital puzzle, secure the prize.",
    "Mental gymnastics with monetary rewards.",
    "Your intelligence is the key to this crypto vault.",
    "Navigate the cryptographic maze to your reward.",
    "Blockchain puzzles with real-world value.",
    "Solve today, profit tomorrow - crypto riddles await.",
    "Where smart contracts meet even smarter solvers.",
    "Tokenized treasures for the truly talented.",
    "Flex your mental muscles and earn digital assets.",
    "The thinking person's path to crypto earnings.",
    "Riddles that reward more than just satisfaction.",
    "Decrypt the challenge, enhance your wallet.",
    "Web3 wisdom pays dividends - literally.",
  ]
  
